name: Post Metrics

on:
  workflow_run:
    workflows: ["Create Metrics"]
    types:
      - completed

jobs:
  post-comment:
    runs-on:
      ubuntu-latest
    if: >
        github.event.workflow_run.event == 'pull_request_target' &&
        github.event.workflow_run.conclusion == 'success'
    permissions:
      pull-requests: write
      actions: read
    steps:
      - name: Download metrics
        uses: actions/download-artifact@v8
        with:
          name: metrics-data
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Post comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
             PR_NUM="$(cat pr_num.txt)"
             gh pr comment $PR_NUM --body-file metrics.md
             MARKER="<!-- PSPTOOL-METRICS-MARKER -->"
             
             COMMENT_ID=$(gh pr view "$PR_NUM" --json comments \
               --template "{{range .comments}}{{if contains .body\"$MARKER\"}}{{.id}}{{\"\n\"}}{{end}}{{end}}"\
               | head -n 1)
             if [ -n "$COMMENT_ID" ]; then
               echo "Updating existing comment $COMMENT_ID"
               gh api -X PATCH "repos/$GH_REPO/issues/comments/$COMMENT_ID" -f body="$(cat metrics.md)"
             else
               echo "Creating new comment"
               gh pr comment "$PR_NUM" --body-file metrics.md
             fi
